/**
 * Configuration loading for claude-imagine — env vars + JSON config file.
 *
 * The config file is generated by `setup.ts` during install, which auto-detects
 * the backend and discovers available models.
 *
 * Priority (highest wins):
 *   1. Environment variables (IMAGINE_SERVER_URL, IMAGINE_BACKEND, IMAGINE_OUTPUT_DIR)
 *   2. JSON config file (~/.config/claude-imagine/config.json)
 *   3. Hardcoded defaults (empty models/imageTypes — requires running install)
 */

import { readFileSync, existsSync } from 'node:fs';
import { homedir } from 'node:os';
import { join } from 'node:path';
import type { ModelDefinition } from './models.js';

export const DEFAULT_SERVER_URL = 'http://localhost:8188';
const DEFAULT_CONFIG_PATH = join(homedir(), '.config', 'claude-imagine', 'config.json');
export const DEFAULT_OUTPUT_DIR = 'generated';

export interface ImagineConfig {
  readonly backend: string;
  readonly serverUrl: string;
  readonly models: Readonly<Record<string, ModelDefinition>>;
  readonly imageTypes: Readonly<Record<string, {
    readonly model: string;
    readonly width?: number;
    readonly height?: number;
  }>>;
  readonly defaultOutputDir: string;
}

export function loadConfig(
  env?: Record<string, string | undefined>,
  configPath?: string,
): ImagineConfig {
  const resolvedEnv = env ?? (process.env as Record<string, string | undefined>);

  let backend = 'comfyui';
  let serverUrl = DEFAULT_SERVER_URL;
  let defaultOutputDir = DEFAULT_OUTPUT_DIR;
  let models: Record<string, ModelDefinition> = {};
  let imageTypes: Record<string, { model: string; width?: number; height?: number }> = {};

  const resolvedConfigPath =
    configPath ??
    resolvedEnv['IMAGINE_CONFIG'] ??
    DEFAULT_CONFIG_PATH;

  if (existsSync(resolvedConfigPath)) {
    try {
      const raw = readFileSync(resolvedConfigPath, 'utf-8');
      const data = JSON.parse(raw) as Record<string, unknown>;

      // Backend
      if (typeof data['backend'] === 'string') {
        backend = data['backend'];
      }

      // Server URL — supports both serverUrl and server.url
      if (typeof data['serverUrl'] === 'string') {
        serverUrl = data['serverUrl'];
      } else {
        const serverSection = (data['server'] ?? {}) as Record<string, unknown>;
        if (typeof serverSection['url'] === 'string') {
          serverUrl = serverSection['url'];
        }
      }

      // Output dir
      if (typeof data['defaultOutputDir'] === 'string') {
        defaultOutputDir = data['defaultOutputDir'];
      } else {
        const outputSection = (data['output'] ?? {}) as Record<string, unknown>;
        if (typeof outputSection['dir'] === 'string') {
          defaultOutputDir = outputSection['dir'];
        }
      }

      // Models section — Record<string, ModelDefinition>
      const modelsSection = data['models'];
      if (modelsSection && typeof modelsSection === 'object' && !Array.isArray(modelsSection)) {
        for (const [id, def] of Object.entries(modelsSection as Record<string, unknown>)) {
          if (!def || typeof def !== 'object') continue;
          const modelDef = def as Record<string, unknown>;
          // Only accept ModelDefinition objects (must have filename)
          if (!('filename' in modelDef)) continue;
          models[id] = {
            id,
            filename: String(modelDef['filename'] ?? ''),
            displayName: String(modelDef['displayName'] ?? id),
            type: (modelDef['type'] === 'unet' ? 'unet' : 'checkpoint') as 'checkpoint' | 'unet',
            tier: (['fast', 'standard', 'high'].includes(modelDef['tier'] as string)
              ? modelDef['tier'] as 'fast' | 'standard' | 'high'
              : undefined),
            params: (modelDef['params'] as Record<string, unknown>) ?? {},
          };
        }
      }

      // Image types section
      const imageTypesSection = data['imageTypes'];
      if (imageTypesSection && typeof imageTypesSection === 'object') {
        for (const [type, assignment] of Object.entries(imageTypesSection as Record<string, unknown>)) {
          const typeUpper = type.toUpperCase();
          if (assignment && typeof assignment === 'object' && 'model' in (assignment as Record<string, unknown>)) {
            const assignObj = assignment as Record<string, unknown>;
            const modelId = String(assignObj['model']);
            const entry: { model: string; width?: number; height?: number } = { model: modelId };
            if (typeof assignObj['width'] === 'number') entry.width = assignObj['width'];
            if (typeof assignObj['height'] === 'number') entry.height = assignObj['height'];
            imageTypes[typeUpper] = entry;
          }
        }
      }
    } catch (e) {
      process.stderr.write(`claude-imagine: config parse error: ${e}\n`);
    }
  }

  // Env var overrides
  if (resolvedEnv['IMAGINE_SERVER_URL']) {
    serverUrl = resolvedEnv['IMAGINE_SERVER_URL'];
  }
  if (resolvedEnv['IMAGINE_BACKEND']) {
    backend = resolvedEnv['IMAGINE_BACKEND'];
  }
  if (resolvedEnv['IMAGINE_OUTPUT_DIR']) {
    defaultOutputDir = resolvedEnv['IMAGINE_OUTPUT_DIR'];
  }

  return { backend, serverUrl, models, imageTypes, defaultOutputDir };
}

/** Resolve a model ID to a ModelDefinition from the config. */
export function resolveModel(
  modelRef: string,
  configModels: Readonly<Record<string, ModelDefinition>>,
): ModelDefinition | undefined {
  return configModels[modelRef];
}

export const CONFIG = loadConfig();
